spring.application.name=empresa-backend

#base de datos y driver de bd
spring.datasource.url=jdbc:sqlite:./data/empresa.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#configurar la persistencia de java
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#script sql de iniciación
spring.sql.init.mode=never

#puerto de inicio
server.port=8080
